# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

  # target 'Demo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Demo

  target 'Demo' do
    pod 'AFNetworking'
    pod 'Masonry'
    #友盟统计分析
    pod 'UMengAnalytics-NO-IDFA'
    # U-Share SDK UI模块（分享面板，建议添加）
    pod 'UMengUShare/UI'
    # 集成微信
    pod 'UMengUShare/Social/WeChat'
    #指纹面容识别
    #pod 'YZAuthID'
    # 集成QQ/QZone/TIM(完整版7.6M)
#    pod 'UMengUShare/Social/QQ'

  end
